#Uncomment this line to define a global platform for your project
   platform :ios, '7.0'

target 'SXK' do
	 pod 'AFNetworking',             '~>3.0.4'
    pod 'Masonry',                  '~> 0.6.3'
    pod 'pop',                      '~> 1.0.8'
    pod 'Mantle',                   '~> 2.0.5'      
    pod 'MJRefresh',                '~> 2.4.12'
    pod 'MBProgressHUD',            '~> 0.9.1'
    pod 'SVProgressHUD'
    pod 'IQKeyboardManager',        '~> 3.3.2'
    pod 'ActionSheetPicker-3.0',    '~> 2.0.3'
    pod 'MWPhotoBrowser',           '~> 2.1.1'
    pod 'SDCycleScrollView',        '~> 1.3'
    pod 'MMPopupView'
	pod 'SDWebImage'	,'~> 3.8.1'
    pod 'MLLabel', '~> 1.9.2'    
    pod 'MJPhotoBrowser', '~> 1.0.2'

pod "Qiniu", :git => 'https://github.com/qiniu/objc-sdk.git', :branch => 'AFNetworking-3.x'
   pod 'Pingpp/Alipay',   '~> 2.2.5'
   pod 'Pingpp/UnionPay',  '~> 2.2.5'
   pod'Pingpp/Wx',  '~> 2.2.5' 	
end

